import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
df = pd.read_csv("Survey-on-Regular-Life-Responses.csv")
print(df.head())
sns.set_style("dark")
sns.set_palette("RdBu")
sns.catplot(x="Age",data=df,kind='count',hue="Gender")
plt.xticks(rotation=30)
sns.catplot(x='All the tasks you have performed, are taking much more time than usual.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are facing a lack of concentration.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are feeling you have no future.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are facing problems with making decisions.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You feel, your life is sad, as there is no joy in your life anymore.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You have lost interest in all things that were important to you once upon a time.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You have been feeling guilty for everything you do.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You have been very irritated and angry recently.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You have been feeling very fatigued.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are feeling that everything you have done has been a failure.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are having suicidal thoughts.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You have lost or gained weight without any diet programs.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are having a loss of appetite.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are having trust issues with everyone around you.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are having trouble in all your relationships (home as well as professional).',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are having a lack of sleep.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are having a problem with your sexual life.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='You are losing interest on your opposite gender.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use the Internet?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='On average, how many hours per day do you spend on the internet?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Which device do you use to use the Internet?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Which internet connection do you use?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='What do you like doing most online?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Chat Rooms]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Instant Messenger]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Social Networking Sites]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Blogs]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Gaming]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Web Browsing]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Music]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [File Sharing]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Shopping]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [News]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you use... [Internet TV]',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Where do you use the internet?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='If you use Internet at home, what room do you use it in?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='What is the main way of communication with your offline friends?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Have you ever met someone in the real world you have only met online?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='If you answered "yes" to the previous question, did you take someone with you?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='How often do you go out in a day?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Do you like outing with friends?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='What kind of person do you think you are?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Does it make you smile?',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
sns.catplot(x='Remark this image.',data=df,kind='count',hue='Gender')
plt.xticks(rotation=30)
plt.show()